# Generated by Django 3.0.7 on 2020-06-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20200624_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
